### ISSUE TITLE
Feature Request: Pause Menu

### ISSUE THREAD

**Issue by Septolum** [dozingcat/Vector-Pinball#10]
It'd be really useful if there was a little pause menu, or even just freeze the action when the menu button (hard or software) is pressed

**Comment by dozingcat** [comment]
You can pause the game by touching the top area where the score is displayed. That should probably be better indicated.

**Comment by Septolum** [comment]
Oh, ok, yea, it might be nice to add support for the hardware (ish) menu
button as well if that's possible

**Comment by dozingcat** [comment]
The back button (or gesture) will also pause the game.
