### ISSUE TITLE
Double gutter bonus

### ISSUE THREAD

**Issue by easyaspi314** [dozingcat/Vector-Pinball#102]
I don't know if this is intentional or not, but it seems like cheese.

With a well timed tap, you can activate two gutter dots when a ball hits a save, one when it enters and one when it bounces out. This makes getting multipliers easier than they should be.

![cheese](https://user-images.githubusercontent.com/6258309/149834685-22219aa0-930c-4db8-b129-d7cd4206f808.gif)

**Comment by dozingcat** [comment]
I'm calling that a feature :)
