### ISSUE TITLE
Translating the text of each table ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [dozingcat/Vector-Pinball#113]
Hi,

I have seen in the github how to translate Vector Pinball (The UI and so on) but i can't find how i can translate the help section of each table.

Can you help me please ?

**Comment by dozingcat** [comment]
The original English text is in `app/src/main/res/values/strings.xml`. In the `strings.xml` file for each language (e.g. `app/src/main/res/values-fr/strings.xml`), you can add entries for `table1_rules`, `table2_rules`, and so on up to 7.

**Comment by Jacques-Olivier-Farcy** [comment]
Ok i made a PR with the french new version.
Maybe you could make an apk for me so i can test it ingame?

**Comment by dozingcat** [comment]
Merged, thanks! I'll build another APK soon.
