### ISSUE TITLE
New feature: A key to reboot the device ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [dozingcat/Vector-Pinball#122]
Hi,

Sometimes the game crash, i don't really why, i can't reproduce it and it is clearly not often.
But could it be possible to have a key, when pressed a long time (3/4 seconds) which will be rebooting the device ?
(As the game start at boot launch in my case)

**Comment by dozingcat** [comment]
That's probably not something that an individual app should be doing, and if the app has crashed, it wouldn't be able to respond to the keypress anyway.

Control-alt-delete might force a reboot according to https://paperlined.org/apps/android/hardware_keyboard.html

**Comment by Jacques-Olivier-Farcy** [comment]
I understand, thanks
