### ISSUE TITLE
New Feature : Highscore ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [dozingcat/Vector-Pinball#123]
Hi,

It would be really nice to have a Highscore system.
Maybe a first step it could be to make highscore locally with just 3 or 4 lettrers per players as it was on old pinballs.

**Comment by pritkr** [comment]
Yes it would be really nice

**Comment by michaelblyons** [comment]
Completed?

**Comment by Jacques-Olivier-Farcy** [comment]
Hi Michael,

I don't think so i don't see the issue number in the last release.

**Comment by dozingcat** [comment]
High scores were added in the 1.11.0 release thanks to @nilsauf
