### ISSUE TITLE
adding sound to the game

### ISSUE THREAD

**Issue by saeed410** [dozingcat/Vector-Pinball#127]
Consider adding sound to the game. This game can be modified similar to musical games. Has anyone tried this feature?How can I do this?

**Comment by Jacques-Olivier-Farcy** [comment]
Hi Saeed,

I am not sure to understand, this game has already sounds and musics.

**Comment by dozingcat** [comment]
Yes, by default the game has sound effects and background music, both of which can be turned on or off in the preferences. Reopen this issue if they're not working for you.
