### ISSUE TITLE
New relese new features ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [dozingcat/Vector-Pinball#162]
Hi @dozingcat ,

Nice to see a new Release here :)
I don't see any description of the release, is there any changes in the game ?

And we are opening an house of video game here in Rennes (France), your game will be a part of it !

Have a nice day

**Comment by dozingcat** [comment]
1.13.0 has a new user-contributed table, and an option to show ball trails. Yes, I should add notes to the Github releases.

Glad to be a part of your arcade!
