### ISSUE TITLE
Free play - Unlimited balls

### ISSUE THREAD

**Issue by a-raccoon** [dozingcat/Vector-Pinball#24]
I really love this game. It's my goto to unwind with its calming wind chime sfx.  Just one thing would make it perfect and that's a Free Play preference for unlimited balls.  Instead of 3 balls (as determined by the table design), the game would keep incremental count of how many balls have been played in the top right.

**Comment by dozingcat** [comment]
I agree that would be a good feature. (So many times on the latest table I end with 11 out of 12 lights...) High scores would be disabled of course. I'll try to add it sometime in the not-too-distant future.

**Comment by dozingcat** [comment]
An option for unlimited balls is added in version 1.5.6, available in the Play store now and hopefully soon on F-Droid.

**Comment by a-raccoon** [comment]
I would like to reopen this suggestion with a slight modification for better enjoyment.

Currently: You have to choose between Normal Play or "[x] Unlimited Balls" at the beginning of the game. But you can't do both.

Suggest: All games start as Normal Play. After the player loses, they can decide to `Continue?` playing or "Try Again?"

This way every game can break the new high score.  And also every game can be played out to the bitter end if they so choose.
