### ISSUE TITLE
Can't start version 1.5.6 on Nexus 7 (2013 version) with Android 6.0.1

### ISSUE THREAD

**Issue by Ertain** [dozingcat/Vector-Pinball#25]
Whenever I try to start version 1.5.6, the app crashes on my tablet.  If you require more information, I can provide that.

**Comment by reno-a** [comment]
Same problem with CyanogenMod (6.0.1)

**Comment by cyberbeat** [comment]
I have the same problem with Cyanogenmod 13 on Samsung S4 mini. I had to install previous version 1.5.5 again.

**Comment by dozingcat** [comment]
Sorry about that. I can't reproduce this on any of my devices. If you can get an ADB log of the crash that would be helpful.

**Comment by Ertain** [comment]
I'll try to get a log to you once I can reinstall the 1.5.6 version.  For some odd reason, I can't access the F-Droid repository.

**Comment by dozingcat** [comment]
It looks like a problem with the F-Droid build, I get a crash on startup using that version as well. They do their own builds from source, I'll let them know something's wrong.

**Comment by reno-a** [comment]
Thank-you.
Effectively, I use a F-Droid build.

Le samedi 12 novembre 2016 à 20:39 -0800, Brian Nenninger a écrit :
> It looks like a problem with the F-Droid build, I get a crash on
> startup using that version as well. They do their own builds from
> source, I'll let them know something's wrong.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 

-- 
R. Aigoin

**Comment by cyberbeat** [comment]
Thanks, it's all fine with the install from play-store.

**Comment by Ertain** [comment]
Btw, the one from F-Droid still doesn't work.

**Comment by dozingcat** [comment]
I sent the F-Droid team an email, haven't heard back yet.

**Comment by tomreyn** [comment]
Thanks for looking into it. It's been 1.5 months with a bunch of holidays in between that you sent this e-mail. Any response, yet? I also tried to ping the f-droid folks on IRC (#fdroid on Freenode in case you would like to try, too). I'll update this post in case I'll receive a response.

**Comment by krt16s** [comment]
@dozingcat: Sorry, that might have gotten lost in the void :/. Will try to have a look at it.

**Comment by krt16s** [comment]
Since older builds from fdroid seem to work and we haven't changed anything at the buildscript itself, the only thing that explains the different sizes are:

* we use the newest NDK that has been installed on the buildserver per default, so that might cause some changes
* a one-time build bug.
