### ISSUE TITLE
netradukeblaj tekstoĉenoj | untranslateaable strings

### ISSUE THREAD

**Issue by verdulo** [dozingcat/Vector-Pinball#39]
Why the strings "about_text" and "table1_rules" are marked with translatable="false"? Can I remove that marker and provide translations?

**Comment by dozingcat** [comment]
`translatable="false"` is just to avoid warnings in Android Studio since currently no other languages have translations for those strings. Yes, you could send a PR removing that setting and adding translations. Thanks!
