### ISSUE TITLE
Game restart happens too quickly

### ISSUE THREAD

**Issue by edam** [dozingcat/Vector-Pinball#4]
This is just a suggestion, but after extensive playing of vector pinball (1.3.1) I have often encountered this scenario:

The last ball goes down at speed.  I'm desperately hitting the screen, trying to smack it back up.  I miss and the ball goes out of play, ending the game suddenly.  One of my presses occurs _after_ the sudden end of game. This press actually starts a new game.

As a result of this scenario, the player will be unable to find out what his previous final score is (unless it was a hiscore). He/she may also be unaware that it _is_ a new game that has started (it's wasn't that obvious when I first started playing, although I can tell now).

Perhaps a solution to this scenario is that, as the game ends, "game over" is displayed for a whole second, during which time presses are ignored.

**Comment by notfoss** [comment]
After trying a few games with the latest version, I can not longer reproduce this issue. Thanks for the fix.

**Comment by vn971** [comment]
Confirming, the interface changed with the latest FDroid version and the issue no longer applies, I think.
