### ISSUE TITLE
Feature Request: Add a ball counter

### ISSUE THREAD

**Issue by ghost** [dozingcat/Vector-Pinball#6]
It would be great, if a ball counter is added to the UI. Currently, there is no way of knowing which ball number one is currently at (apart from the message at the top of the screen, after a ball is lost).

This becomes even more important during a long run, when one is more likely to forget which ball is being used.

Also, if a ball counter is displayed, the player can play more aggressively, or cautiously, depending on how many balls are left.

Thanks

**Comment by notfoss** [comment]
Thanks! I had to wait for the F-droid version to be updated. Ball counter is very useful, also the multiplier counter is great too.
