### ISSUE TITLE
[Accessibility] Touch Target is not respected. 

### ISSUE THREAD

**Issue by andreacantone** [dozingcat/Vector-Pinball#70]
The size of the elements should be at least 48dp*48dp. The following image shows the Unlimited Balls button that does not respect the size of the touch target.

![IMG_20201117_152341](https://user-images.githubusercontent.com/25429624/99403125-682a6800-28ea-11eb-8d1d-ad70cc44c7c2.png)

> **How to reproduce the error**

1. Activate the app [Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=it&gl=US)
2. Open the app [Vector Pinball](https://play.google.com/store/apps/details?id=com.dozingcatsoftware.bouncy&hl=it&gl=US)
3. Activate the registration from the Accessibility Scanner and use the Vector Pinball app.
4. After using the app, stop the recording.

The results will show the errors found in the app. For example:

![IMG_20201117_152308](https://user-images.githubusercontent.com/25429624/99403558-e129bf80-28ea-11eb-80f9-7aed77f55651.png)

**Comment by dozingcat** [comment]
This should be better with the new vertical layout.
