### ISSUE TITLE
Immersive mode

### ISSUE THREAD

**Issue by a1291762** [dozingcat/Vector-Pinball#84]
I find this game frustrating because my thumbs obscure the screen. I try to keep them as low as possible but the nav buttons get in the way (blocking the presses or worse, activate).

It seems to me that Immersive mode was designed for this.

It's as simple as:

    setContentView(R.layout.main);
    View v = findViewById(android.R.id.content);
    v.setSystemUiVisibility(View.SYSTEM_UI_FLAG_IMMERSIVE|View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);

Although maybe it should be a preference? (and there might need to be some version checks depending on the supported Android releases).

I'm happy to do up a pull request. Just making sure this is something that would be accepted.

**Comment by maverick74** [comment]
Plus one for this as well!
(as a preference, naturally)
