### ISSUE TITLE
Localization Platform

### ISSUE THREAD

**Issue by RickyM7** [dozingcat/Vector-Pinball#86]
It would be great if your project were added to some localization platform, such as [Hosted WebLate](https://hosted.weblate.org/hosting/), [POEditor](https://poeditor.com/), etc. These platforms have free plans and make the work of translators much easier.

**Comment by SecularSteve** [comment]
I just wrote the instructions on how to translate this application manually in the currently updated README.md.

It's much easier, and shorter, than it looks. So a hosting site is very redundant in this case.
