### ISSUE TITLE
Feature request: Retain last 'x' high scores

### ISSUE THREAD

**Issue by notfoss** [dozingcat/Vector-Pinball#9]
Currently only one high score is retained, but if possible, I would love to have a dedicated high score menu option showing the last 'x' (say 5) high scores.

Even better would be to have a timestamp next to those high scores, so that we are able to know when we last managed to get a good game. This would be a great motivator to break the previous best high score ;)

**Comment by dozingcat** [comment]
Not quite all of that, but version 1.5 keeps track of the 5 highest scores for each table and cycles through them when a game is not in progress.

**Comment by notfoss** [comment]
Great! It's a nice middle ground till further enhancements. Thanks for that.

**Comment by notfoss** [comment]
Update: I just tested the updated version and the cycling high scores look quite nice :smiley:
