### ISSUE TITLE
Plunger Crash

### ISSUE THREAD

**Issue by VENTDEV** [dozingcat/Vector-Pinball#92]
At the start of a ball, if the plunger doesn't hit the ball hard enough it won't clear the start ramp and then fall back down to the plunger. When that happens the program crashes.

Latest F-Droid build, Android 9

**Comment by dozingcat** [comment]
Should be fixed by https://github.com/dozingcat/Vector-Pinball/commit/7e2f124c809ca1622248f3ad8caf68f8dc407ecb
