### ISSUE TITLE
Mercy Ball

### ISSUE THREAD

**Issue by Strife89** [dozingcat/Vector-Pinball#94]
Here's a feature idea I'd like to suggest, as an option: a ball saver mode, just in case the current ball drains within, say, 10 seconds of being launched.

This happens to me a lot, and it could be that I'm just unskilled, but I'd still like to have such a mercy option for the moments when it seems like I just got unlucky.

Anyway, thank you for making such a good pinball game. :D

**Comment by mdro** [comment]
Seconded. This would be very helpful on the constellations table, where the second or third ball launches into the right save targets and occasionally bounces directly into the left gutter.

**Comment by hackerb9** [comment]
I'd like to see this as well. This is a standard feature in physical pinball machines.

**Comment by hackerb9** [comment]
I'd like to see this as well. This is a standard feature in physical pinball machines.

**Comment by dozingcat** [comment]
Good idea, I'll add it as an option in the next release (whenever that may be).

**Comment by easyaspi314** [comment]
Another related idea is to have a mercy multiplier for if you get a multiplier in the gutter when there is no ball save. It is kinda frustrating how you have to deliberately avoid the rollover in order to avoid losing the extra multiplier.

**Comment by dozingcat** [comment]
Version 1.10.0 adds mercy balls, and preserves multiplier increases if you lose the ball immediately after.
