### ISSUE TITLE
Android TV Optimisation

### ISSUE THREAD

**Issue by SecularSteve** [dozingcat/Vector-Pinball#97]
I just tried this game on a couple of Android TV devices, and it looks and works fantastically with the TV Remote buttons.

Except for the part where I need to **use a mouse** every time I want to choose a map, and start a game.

It would be great if you don't need a touch screen to navigate the menu/game (which in turn, would automatically optimise it for controllers).

**Comment by dozingcat** [comment]
This should be fixed in the current release (1.10.0).
