### ISSUE TITLE
Changing preferences causes crash

### ISSUE THREAD

**Issue by skquinn** [dozingcat/Vector-Pinball#99]
Phone I'm running the app on is a BLU Vivo XI. Any change to the preferences causes a crash and the app will continue to crash on launch until data is cleared (which unfortunately includes the high scores).

I have uninstalled and reinstalled the app and the problem persists. What other information might you need to track this down?

**Comment by CodeShot** [comment]
To add information:

This bug has been reproduced on two devices, both running LineageOS 19+.

Crash:
After opening preferences.
Screen (table rather) is black, points are showing, paddles seem to work.
Menu is showing.
It is as if the board isn't redrawn after the menu is exited.

The game will work if reinstalled, but alas the highscores disappears.

**Comment by skquinn** [comment]
On 11/2/22 15:02, CodeShot wrote:
> To add information:
> 
> This bug has been reproduced on two devices, both running LineageOS 19+.
> 
> Crash:
> After opening preferences.
> Screen (table rather) is black, points are showing, paddles seem to work.
> Menu is showing.
> It is as if the board isn't redrawn after the menu is exited.
> 
> The game will work if reinstalled, but alas the highscores disappears.

The crash I had was the app exiting and the Android system dialog saying 
the program had stopped. I did not get a "playable" black screen. (This 
was on a BLU Vivo XI.)

**Comment by dozingcat** [comment]
I think this is fixed in #141. At least I had a similar bug when running on my Fire stick and it's working fine with that change. "Fortunately", there was a separate bug that caused OpenGL to not be used until you went to the preferences screen and returned, which is the only reason it wasn't crashing all the time.

**Comment by dozingcat** [comment]
Reopen if this is still a problem.
